apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-newsportal
spec:
  type: NodePort
  selector:
    app: pod-label-newsportal
  ports:
    - port: 80 # srv port
      targetPort: 80 # pod port
      nodePort: 30000 # node port