apiVersion: v1
kind: Pod
metadata:
  name: pod-newssystem
  labels:
    app: pod-label-newssystem
spec:
  containers:
    - name: container-newssystem
      image: aluracursos/sistema-noticias:1
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: cm-newssystem