apiVersion: v1
kind: Pod
metadata:
  name: pod-newsdatabase
  labels:
    app: pod-label-newsdatabase
spec:
  containers:
    - name: container-newsdatabase
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      # import all configmap
      envFrom:
        - configMapRef:
            name: cm-newsdatabase


      # define variables here
      # env:
      #   - name: "MYSQL_ROOT_PASSWORD"
      #     value: "q1w2e3r4"
      #   - name: "MYSQL_DATABASE"
      #     value: "empresa"
      #   - name: "MYSQL_PASSWORD"
      #     value: "q1w2e3r4"

      # get isolate config from cm-newsdatabase 
      # env:
      #   - name: MYSQL_ROOT_PASSWORD
      #     valueFrom:
      #       configMapKeyRef:
      #         name: cm-newsdatabase
      #         key: MYSQL_ROOT_PASSWORD